import json
import os
from typing import Dict, List

from src.agents.base_agent import BaseAgent
from src.utils.llm_client import LLMClient


CRITIC_SYSTEM_PROMPT = """
You are a professional Presentation Critic. Your goal is to review slides generated by an automated system and provide constructive, actionable feedback to improve their visual quality and readability.
You may receive images of slides or the slide markdown. You must analyze them for:
1. Content Density: Is there too much text?
2. Layout: Are elements aligned? Is there overlapping?
3. Visuals: Are fonts readable? Is contrast sufficient?
4. Consistency: Are styles consistent across slides?

Return your feedback in JSON. Use the following format:
{
  "feedback": [
    {
      "page_index": 1,
      "severity": "CRITICAL",
      "issue": "Text overflow in code block",
      "position": "Bottom left",
      "suggestion": "Reduce font size or split code into two slides."
    }
  ]
}
If a slide is perfect, you may omit it from the list.
""".strip()


class CriticAgent(BaseAgent):
    def __init__(self, model_name: str = "gpt-4o", provider: str | None = None):
        provider = provider or os.getenv("CRITIC_LLM_PROVIDER") or "moonshot"
        super().__init__(role="Critic", model_name=model_name, provider=provider)
        self.set_system_prompt(CRITIC_SYSTEM_PROMPT)

    def review(self, image_paths: List[str], slides_md: str | None = None) -> List[Dict]:
        if image_paths and self.llm_client.supports_vision():
            prompt = "Review the slides and provide feedback in JSON format."
            response = self.chat(prompt, image_paths=image_paths, json_mode=True)
        else:
            prompt = (
                "Review the slide markdown and provide feedback in JSON format. "
                "Focus on clarity, structure, and potential layout issues.\n\n"
            )
            if slides_md:
                prompt += f"Slides Markdown:\n{slides_md}\n"
            response = self.chat(prompt, json_mode=True)
        payload = LLMClient.safe_json_loads(response.content)
        if isinstance(payload, dict) and "feedback" in payload:
            return payload.get("feedback", [])
        if isinstance(payload, list):
            return payload
        try:
            parsed = json.loads(response.content)
            if isinstance(parsed, dict) and "feedback" in parsed:
                return parsed.get("feedback", [])
            if isinstance(parsed, list):
                return parsed
        except json.JSONDecodeError:
            return []
        return []
