import json
import os
from typing import Dict, List

from agents.base_agent import BaseAgent
from utils.llm_client import LLMClient



EDITOR_SYSTEM_PROMPT_DUAL = """
You are an expert Slidev Developer and Presentation Designer.
Transform raw text into beautiful, structured Slidev markdown slides.

Follow Slidev syntax strictly and output valid Slidev markdown only.

Requirements:
1) Always start with a dedicated title slide (explicitly showing title, subtitle, author, and date) and end with a Thank You/Q&A slide.
2) DO NOT assume frontmatter automatically renders a title page; add an explicit title slide after the frontmatter.
3) DESIGN: Use a consistent color palette and typography. Use Markdown headers (##, ###) to create clear visual hierarchy.
4) Keep a unified visual style across all middle content slides.
5) Use appropriate font sizes; avoid tiny text.
6) Limit text on each slide to 50 words maximum.
7) Use Slidev layouts correctly: `layout` belongs in a slide frontmatter block immediately after `---`.
8) CRITICAL: When defining a layout, DO NOT include any empty lines between the `---` delimiters and the `layout` key!
   Correct Example:
   ---
   layout: center
   ---
   Incorrect Example (FORBIDDEN):
   ---
   
   layout: center
   
   ---
9) Use `---` only once as a separator between slides. Avoid redundant or empty horizontal rules.
10) Do not declare multiple layouts in one slide; create a new slide instead.
11) For two-column layouts, use `layout: two-cols` and `::right::` blocks correctly.
12) You are encouraged to use two-cols layout to enhance visual appeal whenever suitable.
13) You are encouraged to insert a properly sized Mermaid flowchart or a data form to improve clarity whenever helpful.
14) Inside Mermaid nodes, always use `<br/>` for line breaks. Prefer `graph LR` (Left-to-Right) layouts to ensure the diagram fits within the slide width.
15) Make the presentation sufficiently detailed; prefer adding slides over sparse content.
16) Please maintain formulas, code snippets, and any technical details accurately in your slides. Use $\LaTeX$ appropriately.
""".strip()


EDITOR_SYSTEM_PROMPT_SINGLE = """
You are an expert Slidev Developer and Presentation Designer & Critic.
- When asked to generate slides, your task is to transform raw text into beautiful, structured Slidev markdown slides.
    Follow Slidev syntax strictly and output valid Slidev markdown only.

    Requirements:
    1) Always start with a dedicated title slide (explicitly showing title, subtitle, author, and date) and end with a Thank You/Q&A slide.
    2) DO NOT assume frontmatter automatically renders a title page; add an explicit title slide after the frontmatter.
    3) DESIGN: Use a consistent color palette and typography. Use Markdown headers (##, ###) to create clear visual hierarchy.
    4) Keep a unified visual style across all middle content slides.
    5) Use appropriate font sizes; avoid tiny text.
    6) Limit text on each slide to 50 words maximum.
    7) Use Slidev layouts correctly: `layout` belongs in a slide frontmatter block immediately after `---`.
    8) CRITICAL: When defining a layout, DO NOT include any empty lines between the `---` delimiters and the `layout` key!
    Correct Example:
    ---
    layout: center
    ---
    Incorrect Example (FORBIDDEN):
    ---
    
    layout: center
    
    ---
    9) Use `---` only once as a separator between slides. Avoid redundant or empty horizontal rules.
    10) Do not declare multiple layouts in one slide; create a new slide instead.
    11) For two-column layouts, use `layout: two-cols` and `::right::` blocks correctly.
    12) You are encouraged to use two-cols layout to enhance visual appeal whenever suitable.
    13) You are encouraged to insert a properly sized Mermaid flowchart or a data form to improve clarity whenever helpful.
    14) Inside Mermaid nodes, always use `<br/>` for line breaks. Prefer `graph LR` (Left-to-Right) layouts to ensure the diagram fits within the slide width.
    15) Make the presentation sufficiently detailed; prefer adding slides over sparse content.
    16) Please maintain formulas, code snippets, and any technical details accurately in your slides. Use $\LaTeX$ appropriately.
- When asked to critique slides, your task is to review slides generated by an automated system and provide constructive, actionable feedback to improve their visual quality and readability.
    You may receive images of slides or the slide markdown. You must analyze them for:
    1. Title/End Pages: Is there a title and author slide at the beginning? Is there a Thank You or Q&A slide at the end?
    2. Word Limit: Does any slide exceed 80 words?
    3. Consistent Styling: Are the middle content slides visually consistent in layout and typography?
    4. Font Size: Are font sizes appropriate and readable?
    5. Mermaid Use: Where appropriate, is a reasonably sized Mermaid flowchart included to make content more intuitive? Is there any Mermaid flowchart that is fragmented?
    6. Layout & Visuals: Alignment, overlap, contrast, and readability. And check whether the content is out of bounds.

    Return your feedback in JSON. Use the following format:
    {
    "feedback": [
        {
        "page_index": 1,
        "severity": "CRITICAL",
        "category": "Typography",
        "issue": "Font size too small",
        "position": "Body text",
        "evidence": "Body text looks compressed; hard to read at normal zoom.",
        "suggestion": "Increase body font size or reduce bullet count."
        }
    ],
    "summary": {
        "overall_quality": "functional | solid | professional",
        "strengths": ["..."],
        "next_focus": ["..."],
        "improvement_trend": "better | same | worse"
    }
    }
    If a slide is perfect, you may omit it from the list.
    Prioritize critical issues like empty slides, duplicates, dense slides, tiny fonts, and misalignment.
""".strip()



class EditorAgent(BaseAgent):
    def __init__(self, model_name: str = "gpt-5.1", provider: str | None = None):
        provider = provider or os.getenv("EDITOR_LLM_PROVIDER") or "deepseek"
        super().__init__(role="Editor", model_name=model_name, provider=provider)
        mode = os.getenv("MODE") or "dual"
        self.set_system_prompt(EDITOR_SYSTEM_PROMPT_DUAL if mode == "dual" else EDITOR_SYSTEM_PROMPT_SINGLE)

    def generate_outline(self, raw_content: str) -> str:
        prompt = (
            "Create a detailed presentation outline in Markdown. "
            "Include slide order, slide titles, key points (2-4 bullets each), "
            "suggested layout, and any recommended Mermaid diagrams. "
            "Return the outline only.\n\n"
            f"Content:\n{raw_content}\n"
        )
        response = self.chat(prompt)
        return response.content.strip()

    def generate_draft(self, raw_content: str, outline: str | None = None) -> str:
        prompt = (
            "Please convert the following content into Slidev markdown slides. "
            "Ensure the deck is sufficiently detailed by using more slides rather than sparse text. "
            "Return the full slides.md content only.\n\n"
        )
        if outline:
            prompt += f"Outline:\n{outline}\n\n"
        prompt += f"Content:\n{raw_content}\n"
        response = self.chat(prompt)
        return response.content.strip()

    def refine_slides(self, current_code: str, feedback: List[Dict]) -> str:
        feedback_text = json.dumps(feedback, ensure_ascii=False, indent=2)
        prompt = (
            "Please refine the Slidev markdown according to the feedback. "
            "Return the full revised slides.md content only.\n\n"
            f"Current Slides:\n{current_code}\n\n"
            f"Feedback (JSON):\n{feedback_text}\n"
        )
        response = self.chat(prompt)
        return response.content.strip()

    def fix_slides(self, current_code: str, render_error: str) -> str:
        prompt = (
            "The Slidev render failed. Fix the Slidev markdown so it renders successfully. "
            "Only correct syntax, layout, or component usage errors and keep the content intact. "
            "Return the full corrected slides.md content only.\n\n"
            f"Render Error:\n{render_error}\n\n"
            f"Current Slides:\n{current_code}\n"
        )
        response = self.chat(prompt)
        return response.content.strip()
    
    def self_review(self, image_paths: List[str], slides_md: str | None = None) -> List[Dict]:
        if image_paths and self.llm_client.supports_vision():
            prompt = "Review the slides and provide feedback in JSON format."
            response = self.chat(prompt, image_paths=image_paths, json_mode=True)
        else:
            prompt = (
                "Review the slide markdown and provide feedback in JSON format. "
                "Focus on clarity, structure, and potential layout issues.\n\n"
            )
            if slides_md:
                prompt += f"Slides Markdown:\n{slides_md}\n"
            response = self.chat(prompt, json_mode=True)
        payload = LLMClient.safe_json_loads(response.content)
        if isinstance(payload, dict) and "feedback" in payload:
            return payload.get("feedback", [])
        if isinstance(payload, list):
            return payload
        try:
            parsed = json.loads(response.content)
            if isinstance(parsed, dict) and "feedback" in parsed:
                return parsed.get("feedback", [])
            if isinstance(parsed, list):
                return parsed
        except json.JSONDecodeError:
            return []
        return []

